version: "3.9"
name: "megazord"

services:
  backend:
    image: ghcr.io/open-cu/megazord-backend:${BACKEND_IMAGE_TAG:-main}
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG:-False}
      - AUTH_SECRET=${AUTH_SECRET:-secret}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  frontend:
    image: ghcr.io/open-cu/megazord-frontend:${FRONTEND_IMAGE_TAG:-main}
    ports:
      - "3000:3000"
    environment:
      - VITE_API_CLIENT=${VITE_API_CLIENT:-http://localhost:8000/api}
      - VITE_BACKEND_URL=${VITE_BACKEND_URL:-http://localhost:8000}

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
